Index: secure/lib/Makefile
===================================================================
--- secure/lib/Makefile	(revision 340349)
+++ secure/lib/Makefile	(working copy)
@@ -10,6 +10,8 @@
 .endif
 .endif
 
+SUBDIR+=libthreefish
+
 SUBDIR.${MK_TESTS}+= tests
 
 .include <bsd.subdir.mk>
