Index: secure/lib/Makefile
===================================================================
--- secure/lib/Makefile	(revision 329982)
+++ secure/lib/Makefile	(working copy)
@@ -10,6 +10,8 @@
 .endif
 .endif
 
+SUBDIR+=libthreefish
+
 .if ${MK_TESTS} != "no"
 SUBDIR+=tests
 .endif
