Index: lib/geom/eli/Makefile
===================================================================
--- lib/geom/eli/Makefile	(revision 340349)
+++ lib/geom/eli/Makefile	(working copy)
@@ -11,7 +11,7 @@
 SRCS+=	sha256c.c
 SRCS+=	sha512c.c
 
-LIBADD=	md crypto
+LIBADD=	md crypto threefish
 
 WARNS?=	3
 
